language: java

jdk:
  - openjdk8

services:
  - docker

stages:
  - build
  - test
  - build_docker

jobs:
  include:
    - stage: build
      name: "Compilación"
      script:
        - mvn clean compile

    - stage: test
      name: "Pruebas"
      script:
        - mvn test

    - stage: build_docker
      name: "Construcción de imagen de Docker"
      script:
        - docker build -t socket-server -f Dockerfile.server .